const { chromium } = require('/tmp/browser/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true});
  assert(process.env.LEV_ADMIN_PASSWORD, 'Set LEV_ADMIN_USER and LEV_ADMIN_PASSWORD to an existing Lev account');
  const context = await browser.newContext({colorScheme:'dark',viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error=>errors.push(error.message));
  page.on('console', message=>{if(message.type()==='error' && !/401/.test(message.text())) errors.push(message.text());});
  await page.goto('http://127.0.0.1');
  await page.getByRole('heading',{name:'Log in'}).waitFor();
  await page.screenshot({path:'/artifacts/login.png'});
  await page.getByLabel('Username').fill(process.env.LEV_ADMIN_USER);
  await page.getByLabel('Password').fill(process.env.LEV_ADMIN_PASSWORD);
  await page.getByRole('button',{name:'Log in'}).click();
  await page.getByRole('heading',{name:'Incidents',exact:true}).waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.getByLabel('Theme',{exact:true}).selectOption('light');
  await page.reload();
  await page.getByRole('heading',{name:'Incidents',exact:true}).waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await page.getByLabel('Theme',{exact:true}).selectOption('system');
  await page.emulateMedia({colorScheme:'light'});
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  await page.emulateMedia({colorScheme:'dark'});
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
  await page.screenshot({path:'/artifacts/incidents-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Log explorer'}).click();
  await page.getByLabel('Time range').selectOption('2880');
  await page.getByRole('button',{name:'Search logs',exact:true}).click();
  await page.getByRole('heading',{name:'Loaded event distribution'}).waitFor();
  assert(await page.locator('.log-row').count()>0);
  assert(await page.locator('.log-row').first().evaluate(row=>{row.open=true;return row.open;}));
  await page.screenshot({path:'/artifacts/logs-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Sources'}).click();
  await page.getByRole('heading',{name:'Vector sources'}).waitFor();
  assert(await page.locator('.sources tbody tr').count()>0);
  await page.getByLabel('Search',{exact:true}).fill('service=no-such-service-xyz');
  await page.getByText('No source matches this search.').waitFor();
  await page.getByLabel('Search',{exact:true}).fill('');
  await page.screenshot({path:'/artifacts/sources-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:/Incidents/}).click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Horizontal overflow at mobile width');
  await page.screenshot({path:'/artifacts/problems-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Log out'}).click();
  await page.getByRole('heading',{name:'Log in'}).waitFor();
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: login/logout, log search, event expansion, desktop/mobile layout and no browser errors.');
})().catch(error=>{console.error(error);process.exit(1);});
